// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://api.openweathermap.org/data/2.5',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR']
};
